package com.mycompany.sistema_de_biblioteca;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;

public class BookManager extends javax.swing.JFrame {
    Connection cnn;
    private Statement stm;
    private boolean yaEsta = false;
    ArrayList<Genero> Generos  = new ArrayList<>();
    
    public BookManager(Connection cnn) {
        this.cnn=cnn;
        initComponents();
        
    }
    
    private ComboBoxModel<String> FillComboboxGeneros() {
        try {
            stm = cnn.createStatement();
            ResultSet rs = stm.executeQuery("SELECT Id, Descripcion FROM generos ORDER BY Id");
            while(rs.next())
                Generos.add(new Genero(rs.getInt("Id"), rs.getString("Descripcion")));
            rs.close();
            String[] str = new String[Generos.size()];
            for(int i=0; i < Generos.size(); i++) {
                str[i]=Generos.get(i).getDescripcion();
            }
            ComboBoxModel model = new DefaultComboBoxModel(str);
            return model;
        } catch (SQLException ex) {
            System.out.println("MySQL ERROR: " + ex.getMessage());
            return null;
        }
    }   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pActions = new javax.swing.JPanel();
        bSave = new javax.swing.JButton();
        bPortada = new javax.swing.JButton();
        lEsta = new javax.swing.JLabel();
        pDataBook = new javax.swing.JPanel();
        lISBN = new javax.swing.JLabel();
        tISBN = new javax.swing.JTextField();
        lTitulo = new javax.swing.JLabel();
        tTitulo = new javax.swing.JTextField();
        lAutor = new javax.swing.JLabel();
        tAutor = new javax.swing.JTextField();
        cbGenero = new javax.swing.JComboBox<>();
        lGenero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pActions.setBackground(new java.awt.Color(255, 220, 156));

        bSave.setBackground(new java.awt.Color(137, 104, 31));
        bSave.setText("Guardar");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bPortada.setBackground(new java.awt.Color(188, 119, 94));
        bPortada.setText("Borrar");
        bPortada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPortadaActionPerformed(evt);
            }
        });

        lEsta.setText("jLabel1");

        javax.swing.GroupLayout pActionsLayout = new javax.swing.GroupLayout(pActions);
        pActions.setLayout(pActionsLayout);
        pActionsLayout.setHorizontalGroup(
            pActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pActionsLayout.createSequentialGroup()
                .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lEsta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 673, Short.MAX_VALUE))
        );
        pActionsLayout.setVerticalGroup(
            pActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lEsta))
        );

        pDataBook.setBackground(new java.awt.Color(253, 250, 245));
        pDataBook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lISBN.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lISBN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lISBN.setText("ISBN");

        tISBN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tISBNFocusLost(evt);
            }
        });

        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lTitulo.setText("Título");

        lAutor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lAutor.setText("Autor");

        cbGenero.setModel(FillComboboxGeneros());

        lGenero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lGenero.setText("Género");

        javax.swing.GroupLayout pDataBookLayout = new javax.swing.GroupLayout(pDataBook);
        pDataBook.setLayout(pDataBookLayout);
        pDataBookLayout.setHorizontalGroup(
            pDataBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataBookLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pDataBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lAutor)
                    .addComponent(lTitulo)
                    .addComponent(lISBN)
                    .addComponent(lGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDataBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tISBN, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTitulo)
                    .addComponent(tAutor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pDataBookLayout.setVerticalGroup(
            pDataBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataBookLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pDataBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lISBN)
                    .addComponent(tISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDataBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTitulo)
                    .addComponent(tTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDataBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAutor)
                    .addComponent(tAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDataBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lGenero))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pDataBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pDataBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        try {
            int idGenero=0;
            for(int i = 0; i < Generos.size(); i++) {
                if(Generos.get(i).getDescripcion().compareTo(cbGenero.getSelectedItem().toString())==0)
                    idGenero=Generos.get(i).getId();
            }
            stm = cnn.createStatement();
            String strCommand = "INSERT INTO Books (Titulo, Autor, Genero, ISBN) VALUES (?, ?, ?, ?)";
            if(yaEsta)
                strCommand="UPDATE Books SET Titulo=?, Autor=?, Genero=? WHERE ISBN=?";
            PreparedStatement pst = cnn.prepareStatement(strCommand);
            pst.setString(1, tTitulo.getText());
            pst.setString(2, tAutor.getText());
            pst.setInt(3, idGenero);
            pst.setString(4, tISBN.getText());
            pst.execute();
            pst.close();
        } catch (SQLException ex) {
            System.out.println("MySQL ERROR: " + ex.getMessage());
        }
    }//GEN-LAST:event_bSaveActionPerformed

    private void tISBNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tISBNFocusLost
        try {
            stm = cnn.createStatement();
            ResultSet rs = stm.executeQuery("SELECT Titulo, Autor, Genero FROM Books WHERE ISBN='" + tISBN.getText() + "'");
            yaEsta=rs.next();
            if(yaEsta) {
                lEsta.setText("Si esta");
                tTitulo.setText(rs.getString("Titulo"));
                tAutor.setText(rs.getString("Autor"));
                for(int i=0; i<Generos.size(); i++) 
                    if(Generos.get(i).getId() == rs.getInt("Genero"))
                        cbGenero.setSelectedItem(Generos.get(i).getDescripcion());
            }    
            else {                
                lEsta.setText("NO ESTÁ");
                tTitulo.setText("");
                tAutor.setText("");
                cbGenero.setSelectedIndex(0);
            }    
            rs.close();
       } catch (SQLException ex) {
            System.out.println("MySQL ERROR: " + ex.getMessage());
       }
    }//GEN-LAST:event_tISBNFocusLost

    private void bPortadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPortadaActionPerformed
        JFileChooser dlgFile = new JFileChooser();
        if(dlgFile.showDialog(this,"Ok")==JFileChooser.APPROVE_OPTION) {
            try {
                PreparedStatement pst = cnn.prepareStatement("UPDATE books SET Portada=? WHERE ISBN=?");
                FileInputStream filestream = new FileInputStream(dlgFile.getSelectedFile());
                pst.setBinaryStream(1, filestream, dlgFile.getSelectedFile().length());
                pst.executeUpdate();
                pst.close();
            } catch (SQLException | FileNotFoundException ex) {
                System.out.println("ERROR: " + ex.getMessage());
            }
        }    
    }//GEN-LAST:event_bPortadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookManager().setVisible(true);
            }
        });
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPortada;
    private javax.swing.JButton bSave;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JLabel lAutor;
    private javax.swing.JLabel lEsta;
    private javax.swing.JLabel lGenero;
    private javax.swing.JLabel lISBN;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JPanel pActions;
    private javax.swing.JPanel pDataBook;
    private javax.swing.JTextField tAutor;
    private javax.swing.JTextField tISBN;
    private javax.swing.JTextField tTitulo;
    // End of variables declaration//GEN-END:variables
}
